### ISSUE TITLE
Use browserlist?

### ISSUE THREAD

**Issue by dtognazzini** [Invoca/backdraft#87]
Should we use browserlist to specify supported browsers when building dist files?

Consumers that import ES6 modules won't need this. This would only affect down-rev consumers that consume the dist.

**Comment by nburwell** [comment]
I'm in support of this, and would have the list be:

* Last 2 versions of Chrome, Safari, Firefox, MS Edge
* IE11

**Comment by dtognazzini** [comment]
When using Webpack and babel-preset-env, transpilation will target ES5 for the dist file. We are upgrading Backdraft to allow consumers to pull in Backdraft files as ES6 modules. When pulling in as ES6 modules, consumers won't use the dist file. Consumers that pull in ES6 modules should use browserslist during their bundling process.

I'm closing this for now since the forward-looking path is to support consumers sourcing ES6 modules.
